config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # read all
  get "tasks", to: "tasks#index"
  #create
  get "tasks/new", to: "tasks#new", as: :new_task
  post "tasks", to: "tasks#create"
  #read one
  get "tasks/:id", to: "tasks#show", as: :task
  #update
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  #delete
  delete "tasks/:id", to: "tasks#destroy", as: :destroy_task
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show

  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit

  end

  def update

    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy

    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |x| %>
  <%= x.label :title %>
  <%= x.text_field :title %>
  <%= x.label :details %>
  <%= x.text_field :details %>
  <%= x.label :completed%>
  <%= x.check_box :completed %>
  <%= x.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Update a task</h1>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="container">
  <h1 class=" d-flex justify-content-center">My Tasks</h1>
  <div class="d-flex justify-content-center">
    <ul class="list-unstyled">
      <% @tasks.each do |task| %>
        <li><%= link_to task.title, task_path(task) %>: done =  <input type="checkbox" <%= task.completed ? 'checked' : '' %>></li>
      <% end %>
    </ul>
  </div>
  <div class=" d-flex justify-content-center">
    <%= link_to "Add", new_task_path %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>Add a task to list</h1>
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1>Task Details</h1>
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p>completed? <input type="checkbox"<%= @task.completed ? 'checked' : '' %>></p>
<%= link_to "Edit task", edit_task_path(@task) %>
<%= link_to "Delete", destroy_task_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
<%= link_to "Back to tasks", tasks_path %>